---
- name: nmap install lab
  hosts: localhost
  become: true
  tasks:
  - name: nmap installation
    apt:
     name: nmap
     state: latest
     update_cache: true
  - name: copy targets
    copy:
     src: ./targets.txt
     dest: ~/targets.txt
     force: yes
     mode: 0644
  - name: nmap run
    shell: "nmap -iL targets.txt -p 80 -oG -"
    register: output_nmap
  - name: nmap output
    debug:
     msg: "{{output_nmap.stdout_lines}}"
